name: Markdown spellcheck

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: errata-ai/vale-action@v2.1.1
        with:
          files: pages
          fail_on_error: true

